runtime: python
env: flex
entrypoint: gunicorn -b 0.0.0.0:8080 dashboard_metrics:server

runtime_config:
  python_version: 3.7

resources:
  cpu: 2
  memory_gb: 2
  disk_size_gb: 10

manual_scaling:
  instances: 1

env_variables:
  ELEPHANTSQL_URL: "postgres://msydzjhv:bRRyUHzKCCwgLoP_lhECiyT1AoXwPBJ6@drona.db.elephantsql.com/msydzjhv"

